models/produtos.py
import os

from dotenv import load_dotenv
from peewee import CharField, FloatField, IntegerField, Model, MySQLDatabase

load_dotenv()

MYSQL_USER=os.getenv('MYSQL_USER')
MYSQL_PASSWORD=os.getenv('MYSQL_PASSWORD')
MYSQL_DB=os.getenv('MYSQL_DB')
MYSQL_HOST=os.getenv('MYSQL_HOST')

mysql_db = MySQLDatabase(MYSQL_DB, user=MYSQL_USER, password=MYSQL_PASSWORD, host=MYSQL_HOST, port=3306)

class Produtos(Model):
    id = IntegerField(primary_key=True)
    nome = CharField(max_length=100)
    descricao = CharField(max_length=200)
    preco = FloatField()
    quantidade = IntegerField()
    class Meta:
        database = mysql_db
        

models/registro.py
from flask_login import UserMixin
from peewee import AutoField, BooleanField, CharField, Model

from models.produtos import mysql_db


class Usuarios(UserMixin, Model):
    id = AutoField()
    username = CharField(max_length= 150)
    senha = CharField(max_length=255)
    
    class Meta:
        database = mysql_db
    

app.py
import os

from dotenv import load_dotenv
from flask import Blueprint, Flask, render_template
from flask_login import LoginManager

from models.registro import Usuarios
from routes.auth import auth_route
from routes.home import home_route
from routes.produtos import rota_produtos

load_dotenv()

app = Flask(__name__)
app.secret_key = os.getenv('SECRETKEY')

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "auth.login"

@login_manager.user_loader
def user_loader(id):
    return Usuarios.get_or_none(Usuarios.id == id)

app.register_blueprint(home_route)
app.register_blueprint(rota_produtos, url_prefix='/produtos')
app.register_blueprint(auth_route, url_prefix="/auth")


app.run(debug=True)

routes/auth.py
import flask
from flask import (Blueprint, Flask, flash, jsonify, redirect, render_template,
                   request, url_for)
from flask_login import login_user, logout_user

from models.registro import Usuarios, mysql_db

auth_route = Blueprint('auth', __name__)

@auth_route.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['usernameForm'].lower()
        senha = request.form['senhaForm']
        
        user = Usuarios.get_or_none(Usuarios.username == username)
        if user and user.senha == senha:
            login_user(user)
            response = jsonify({"message": "Login bem-sucedido"})
            response.headers['HX-Redirect'] = url_for('home.home')
            return response
        else:
            flash('Usuário ou senha incorretos')
            response = jsonify({"message": "Login mal-sucedido"})
            response.headers['HX-Redirect'] = url_for('auth.login')
            return response, 403
    return render_template('login.html')

@auth_route.route('/registro', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['usernameForm'].lower()
        senha = request.form['senhaForm']
        
        if not Usuarios.get_or_none(Usuarios.username == username):
            user = Usuarios(username=username, senha=senha)
            user.save()
            response = jsonify({"message": "Login bem-sucedido"})
            response.headers['HX-Redirect'] = url_for('auth.login')
            return response
        else:
            flash('Usuário já existente')
            response = jsonify({"message": "Login mal-sucedido"})
            response.headers['HX-Redirect'] = url_for('auth.register')
            return response, 403
    return render_template('register.html')

@auth_route.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

routes/home.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_required

home_route = Blueprint('home', __name__)
@home_route.route('/')
@login_required
def home():
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    return render_template('index.html', user = current_user)

routes/produtos.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import login_required
from peewee import IntegrityError

from models.produtos import Produtos, mysql_db

rota_produtos = Blueprint('produtos', __name__)

mysql_db.connect()

@rota_produtos.route('/')
def listarProdutos():
    produtos = Produtos.select()
    return render_template('listar_produtos.html', produtos=produtos)

@rota_produtos.route('/adicionar')
def form_adicionar():
    return render_template('adicionar.html')

@rota_produtos.route('/', methods=["POST"])
@login_required
def adicionar():
    id = int(request.form['id'])
    nome = request.form['nome'].strip()
    descricao = request.form['descricao'].strip()
    preco = float(request.form['preco'])
    quantidade = int(request.form['quantidade'])
        
    produto_existente = Produtos.select().where(Produtos.id == id).first()
    
    if produto_existente:
        return redirect(url_for('produtos.form_adicionar')), 302
    else:
        novo_produto = Produtos.create(id=id, nome=nome, descricao=descricao, preco=preco, quantidade=quantidade)
        return render_template('produto.html', produto=novo_produto), 200
    
@rota_produtos.route('/<int:produto_id>/delete', methods=["DELETE"])
def deletar_produto(produto_id):
    produto = Produtos.get_by_id(produto_id)
    produto.delete_instance()
    return '', 200

@rota_produtos.route('/<int:produto_id>/edit')
def form_editar_produto(produto_id):
    produto = Produtos.get_or_none(produto_id)
    return render_template('adicionar.html', produto=produto)

@rota_produtos.route('/<int:produto_id>/edit_product',methods=['PUT'])
def editar_produto(produto_id):
    data = request.form
    
    produto_editado = Produtos.get_by_id(produto_id)
    
    produto_editado.nome = data['nome']
    produto_editado.descricao = data['descricao']
    produto_editado.preco = data['preco']
    produto_editado.quantidade = data['quantidade']
    produto_editado.save()
    return render_template("produto.html", produto=produto_editado)
    
@rota_produtos.route('/search')
def pesquisa():
    q = request.args.get('q')
    if q:
        results = Produtos.select().where(Produtos.nome.contains(q) | Produtos.descricao.contains(q))
    else:
        results = Produtos.select()
    return render_template('pesquisa_parcial.html', results=results)

templates/adicionar.html
<form
  {%
  if
  produto
  %}
  hx-put="{{url_for('produtos.editar_produto', produto_id=produto.id)}}"
  method="PUT"
  hx-target="#produto-{{produto.id}}"
  hx-swap="outerHTML"
  {%
  else
  %}
  hx-post="{{ url_for('produtos.adicionar') }}"
  method="POST"
  hx-target="#lista-produtos-target"
  hx-swap="beforeend"
  {%
  endif
  %}
  class="row g-3"
  hx-on::after-request="if(event.detail.successful) window.location.reload()"
>
  <div class="col-md-2">
    <label class="form-label">ID:</label>
    <input
      class="form-control"
      type="number"
      name="id"
      required
      {%
      if
      produto
      %}
      readonly
      value="{{produto.id}}"
      {%
      endif
      %}
    />
  </div>

  <div class="col-md-3">
    <label class="form-label">Nome:</label>
    <input
      class="form-control"
      type="text"
      name="nome"
      required
      {%
      if
      produto
      %}
      value="{{produto.nome}}"
      {%
      endif
      %}
    />
  </div>
  <div class="col-md-3">
    <label class="form-label">Descricão:</label>
    <input
      class="form-control"
      type="text"
      name="descricao"
      required
      {%
      if
      produto
      %}
      value="{{produto.descricao}}"
      {%
      endif
      %}
    />
  </div>
  <div class="col-md-2">
    <label class="form-label">Preco:</label>
    <input
      class="form-control"
      type="number"
      step="0.01"
      name="preco"
      required
      {%
      if
      produto
      %}
      value="{{produto.preco}}"
      {%
      endif
      %}
    />
  </div>
  <div class="col-md-2">
    <label class="form-label">Quantidade:</label>
    <input
      class="form-control"
      type="number"
      name="quantidade"
      required
      {%
      if
      produto
      %}
      value="{{produto.quantidade}}"
      {%
      endif
      %}
    />
  </div>
  <div class="col-12">
    <button class="btn btn-primary" type="submit">
      {%if produto%} Salvar Produto{% else %} Adicionar Produto {%endif%}
    </button>
  </div>
</form>

templates/index.html
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Lojas 12</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://unpkg.com/htmx.org@2.0.2"
      integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="container">
      <h1 class="text-center">Gestão de Produtos</h1>
      <p>Seja bem vindo(a): {{ user.username }} <a href="{{url_for('auth.logout')}}" class="link-underline-light">Sair</a></p>
      <div class="container mt-5">
        <h3 class="text-center">Pesquisar Produtos</h3>
        <div class="row">
          <div class="mb-3 d-flex justify-content-center">      
            <input
            type="text"
            class="input-group-text form-control w-100 text-start"
            placeholder="Pesquise..."
            name="q"
            hx-get="{{url_for('produtos.pesquisa')}}"
            hx-trigger="keyup changed delay:500ms"
            hx-target="#lista-produtos-target"
          />
        </div>
      </div>
      <div
        id="form-produto"
        hx-get="{{url_for('produtos.form_adicionar')}}"
        hx-trigger="load"
      ></div>
      <hr />
      <div
        hx-get="{{url_for('produtos.listarProdutos')}}"
        hx-trigger="load"
      ></div>
    </div>
  </body>
</html>

templates/listar_produtos.html
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Descricao</th>
      <th scope="col">Preco</th>
      <th scope="col">Quantidade</th>
    </tr>
  </thead>
  <tbody id="lista-produtos-target">
    {% for produto in produtos %} {%include 'produto.html'%} {% endfor %}
  </tbody>
</table>

templates/login.html
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Register</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://unpkg.com/htmx.org@2.0.2"
      integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="container">
      <form class="row g-3" hx-post="{{url_for('auth.login')}}" method="post">
        <h1 class="text-center">Login</h1>
        {% set msgs = get_flashed_messages() %} {% if msgs %}
        <div class="text-danger">
          {% for msg in msgs %} {{ msg }} {% endfor %}
        </div>
        {% endif %}
        <div class="mb-2 w-50">
          <label for="exampleFormControlInput1" class="col-sm-2 col-form-label"
            >Username</label
          >
          <input
            type="input"
            class="form-control"
            id="exampleFormControlInput1"
            name="usernameForm"
            required
          />
        </div>
        <div class="mb-2 w-50">
          <label for="inputPassword2" class="col-sm-2 col-form-label"
            >Password</label
          >
          <input
            type="password"
            class="form-control"
            id="inputPassword2"
            placeholder="Password"
            name="senhaForm"
            required
          />
        </div>
        <div class="mb-2">
          <button type="submit" class="btn btn-primary mb-3">Entrar</button>
        </div>
        <div class="col-12">
          <p>
            Ainda não tem uma conta?
            <a href="{{ url_for('auth.register') }}">Registre-se</a>
          </p>
        </div>
      </form>
    </div>
  </body>
</html>

templates/pesquisa_parcial.html
{% for produto in results %}
<tr id="produto-{{produto.id}}">
  <td>{{produto.id}}</td>
  <td>{{produto.nome}}</td>
  <td>{{produto.descricao}}</td>
  <td>{{produto.preco}}</td>
  <td>{{produto.quantidade}}</td>
  <td>
    <button
      class="btn btn-primary"
      hx-get="{{url_for('produtos.form_editar_produto', produto_id=produto.id)}}"
      hx-target="#form-produto"
      hx-trigger="click"
    >
      Editar
    </button>
    <button
      class="btn btn-danger"
      hx-delete="{{url_for('produtos.deletar_produto', produto_id=produto.id)}}"
      hx-target="closest tr"
      hx-swap="outerHTML"
      hx-trigger="click"
    >
      Deletar
    </button>
  </td>
</tr>
{% endfor %}

templates/produto.html
<tr>
  <th scope="row">{{produto.id}}</th>
  <td>{{produto.nome}}</td>
  <td>{{produto.descricao}}</td>
  <td>{{produto.preco}}</td>
  <td>{{produto.quantidade}}</td>
  <td>
    <button class="btn btn-primary">Editar</button>
    <button
      class="btn btn-danger"
      hx-delete="{{url_for('produtos.deletar_produto', produto_id=produto.id)}}"
      hx-target="closest tr"
      hx-swap="outerHTML"
      hx-trigger="click"
    >
      Deletar
    </button>
  </td>
</tr>

templates/register.html
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Register</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://unpkg.com/htmx.org@2.0.2"
      integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ"
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div class="container">
      <form
        class="row g-3"
        hx-post="{{url_for('auth.register')}}"
        method="post"
      >
        <h1 class="text-center">Registrar</h1>
        {% set msgs = get_flashed_messages() %} {% if msgs %}
        <div class="text-danger">
          {% for msg in msgs %} {{ msg }} {% endfor %}
        </div>
        {% endif %}
        <div class="mb-2 w-50">
          <label for="exampleFormControlInput1" class="col-sm-2 col-form-label"
            >Username</label
          >
          <input
            type="input"
            class="form-control"
            id="exampleFormControlInput1"
            name="usernameForm"
            required
          />
        </div>
        <div class="mb-2 w-50">
          <label for="inputPassword2" class="col-sm-2 col-form-label"
            >Senha</label
          >
          <input
            type="password"
            class="form-control"
            id="inputPassword2"
            placeholder="Password"
            name="senhaForm"
            required
          />
        </div>
        <div class="mb-2">
          <button type="submit" class="btn btn-primary mb-3">Registrar</button>
        </div>
        <div class="col-12">
          <p>
            Já tem uma conta?
            <a href="{{ url_for('auth.login') }}">Faça login</a>
          </p>
        </div>
      </form>
    </div>
  </body>
</html>